// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

package hello

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SayHelloMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SayHelloMessage) Reset()         { *m = SayHelloMessage{} }
func (m *SayHelloMessage) String() string { return proto.CompactTextString(m) }
func (*SayHelloMessage) ProtoMessage()    {}
func (*SayHelloMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{0}
}

func (m *SayHelloMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayHelloMessage.Unmarshal(m, b)
}
func (m *SayHelloMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayHelloMessage.Marshal(b, m, deterministic)
}
func (m *SayHelloMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayHelloMessage.Merge(m, src)
}
func (m *SayHelloMessage) XXX_Size() int {
	return xxx_messageInfo_SayHelloMessage.Size(m)
}
func (m *SayHelloMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SayHelloMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SayHelloMessage proto.InternalMessageInfo

type SayHelloResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SayHelloResponse) Reset()         { *m = SayHelloResponse{} }
func (m *SayHelloResponse) String() string { return proto.CompactTextString(m) }
func (*SayHelloResponse) ProtoMessage()    {}
func (*SayHelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{1}
}

func (m *SayHelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayHelloResponse.Unmarshal(m, b)
}
func (m *SayHelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayHelloResponse.Marshal(b, m, deterministic)
}
func (m *SayHelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayHelloResponse.Merge(m, src)
}
func (m *SayHelloResponse) XXX_Size() int {
	return xxx_messageInfo_SayHelloResponse.Size(m)
}
func (m *SayHelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SayHelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SayHelloResponse proto.InternalMessageInfo

func (m *SayHelloResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*SayHelloMessage)(nil), "SayHelloMessage")
	proto.RegisterType((*SayHelloResponse)(nil), "SayHelloResponse")
}

func init() { proto.RegisterFile("hello.proto", fileDescriptor_61ef911816e0a8ce) }

var fileDescriptor_61ef911816e0a8ce = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x48, 0xcd, 0xc9,
	0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x12, 0xe4, 0xe2, 0x0f, 0x4e, 0xac, 0xf4, 0x00,
	0x89, 0xf8, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x2a, 0xa9, 0x70, 0x09, 0xc0, 0x84, 0x82, 0x52,
	0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x04, 0xb8, 0x98, 0x73, 0x8b, 0xd3, 0x25, 0x18, 0x15,
	0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0xa3, 0x0a, 0x2e, 0x1e, 0xb0, 0x92, 0xe0, 0xd4, 0xa2, 0xb2,
	0xcc, 0xe4, 0x54, 0x21, 0x3d, 0x2e, 0x56, 0xf7, 0xa2, 0xd4, 0xd4, 0x12, 0x21, 0x01, 0x3d, 0x34,
	0x03, 0xa5, 0x04, 0xf5, 0xd0, 0xcd, 0x53, 0x62, 0x10, 0xb2, 0xe0, 0xe2, 0x06, 0xab, 0x0f, 0x2e,
	0x29, 0x4a, 0x4d, 0xcc, 0x25, 0x52, 0x97, 0x06, 0xa3, 0x01, 0x63, 0x12, 0x1b, 0xd8, 0xe5, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x10, 0xb6, 0x9a, 0xc8, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloServiceClient is the client API for HelloService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloServiceClient interface {
	Greet(ctx context.Context, in *SayHelloMessage, opts ...grpc.CallOption) (*SayHelloResponse, error)
	GreetStream(ctx context.Context, opts ...grpc.CallOption) (HelloService_GreetStreamClient, error)
}

type helloServiceClient struct {
	cc *grpc.ClientConn
}

func NewHelloServiceClient(cc *grpc.ClientConn) HelloServiceClient {
	return &helloServiceClient{cc}
}

func (c *helloServiceClient) Greet(ctx context.Context, in *SayHelloMessage, opts ...grpc.CallOption) (*SayHelloResponse, error) {
	out := new(SayHelloResponse)
	err := c.cc.Invoke(ctx, "/HelloService/Greet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloServiceClient) GreetStream(ctx context.Context, opts ...grpc.CallOption) (HelloService_GreetStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_HelloService_serviceDesc.Streams[0], "/HelloService/GreetStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloServiceGreetStreamClient{stream}
	return x, nil
}

type HelloService_GreetStreamClient interface {
	Send(*SayHelloMessage) error
	Recv() (*SayHelloResponse, error)
	grpc.ClientStream
}

type helloServiceGreetStreamClient struct {
	grpc.ClientStream
}

func (x *helloServiceGreetStreamClient) Send(m *SayHelloMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *helloServiceGreetStreamClient) Recv() (*SayHelloResponse, error) {
	m := new(SayHelloResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HelloServiceServer is the server API for HelloService service.
type HelloServiceServer interface {
	Greet(context.Context, *SayHelloMessage) (*SayHelloResponse, error)
	GreetStream(HelloService_GreetStreamServer) error
}

// UnimplementedHelloServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHelloServiceServer struct {
}

func (*UnimplementedHelloServiceServer) Greet(ctx context.Context, req *SayHelloMessage) (*SayHelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Greet not implemented")
}
func (*UnimplementedHelloServiceServer) GreetStream(srv HelloService_GreetStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GreetStream not implemented")
}

func RegisterHelloServiceServer(s *grpc.Server, srv HelloServiceServer) {
	s.RegisterService(&_HelloService_serviceDesc, srv)
}

func _HelloService_Greet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayHelloMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).Greet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HelloService/Greet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).Greet(ctx, req.(*SayHelloMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelloService_GreetStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HelloServiceServer).GreetStream(&helloServiceGreetStreamServer{stream})
}

type HelloService_GreetStreamServer interface {
	Send(*SayHelloResponse) error
	Recv() (*SayHelloMessage, error)
	grpc.ServerStream
}

type helloServiceGreetStreamServer struct {
	grpc.ServerStream
}

func (x *helloServiceGreetStreamServer) Send(m *SayHelloResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *helloServiceGreetStreamServer) Recv() (*SayHelloMessage, error) {
	m := new(SayHelloMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _HelloService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "HelloService",
	HandlerType: (*HelloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greet",
			Handler:    _HelloService_Greet_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GreetStream",
			Handler:       _HelloService_GreetStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "hello.proto",
}
